const alphabet = {
  "default": {
    "offsetLeft": -50,
    "offsetRight": -25,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 60,
    "centerValY": 0,
    "leftVal": 0,
    "rightVal": 50,
    "topVal": 100,
    "bottomVal": 0
  },
  "A": {
    "offsetLeft": 0,
    "offsetRight": 0,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 100,
    "centerValY": 0,
    "leftVal": 100,
    "rightVal": 100,
    "topVal": 100,
    "bottomVal": 0
  },
  "B": {
    "offsetLeft": 0,
    "offsetRight": 0,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 100,
    "centerValY": 0,
    "leftVal": 100,
    "rightVal": 60,
    "topVal": 60,
    "bottomVal": 60
  },
  "C": {
    "offsetLeft": 0,
    "offsetRight": 0,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 0,
    "centerValY": 0,
    "leftVal": 100,
    "rightVal": 0,
    "topVal": 100,
    "bottomVal": 100
  },
  "D": {
    "offsetLeft": 0,
    "offsetRight": 0,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 0,
    "centerValY": 0,
    "leftVal": 100,
    "rightVal": 60,
    "topVal": 60,
    "bottomVal": 60
  },
  "E": {
    "offsetLeft": 0,
    "offsetRight": 0,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 100,
    "centerValY": 0,
    "leftVal": 100,
    "rightVal": 0,
    "topVal": 100,
    "bottomVal": 100
  },
  "F": {
    "offsetLeft": 0,
    "offsetRight": 0,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 100,
    "centerValY": 0,
    "leftVal": 100,
    "rightVal": 0,
    "topVal": 100,
    "bottomVal": 0
  },
  "G": {
    "offsetLeft": 0,
    "offsetRight": 25,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 0,
    "centerValY": 20,
    "leftVal": 100,
    "rightVal": 50,
    "topVal": 100,
    "bottomVal": 100
  },
  "H": {
    "offsetLeft": 0,
    "offsetRight": 0,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 100,
    "centerValY": 0,
    "leftVal": 100,
    "rightVal": 100,
    "topVal": 0,
    "bottomVal": 0
  },
  "I": {
    "offsetLeft": 0,
    "offsetRight": 0,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 0,
    "centerValY": 100,
    "leftVal": 0,
    "rightVal": 0,
    "topVal": 100,
    "bottomVal": 100
  },
  "J": {
    "offsetLeft": 0,
    "offsetRight": 0,
    "offsetTop": 0,
    "offsetBottom": -25,
    "centerValX": 0,
    "centerValY": 100,
    "leftVal": 0,
    "rightVal": 0,
    "topVal": 100,
    "bottomVal": 50
  },
  "K": {

    "offsetLeft": 0,
    "offsetRight": 35,
    "offsetTop": 35,
    "offsetBottom": -50,
    "centerValX": 100,
    "centerValY": 60,
    "leftVal": 100,
    "rightVal": 30,
    "topVal": 30,
    "bottomVal": 0
  },
  "L": {
    "offsetLeft": 0,
    "offsetRight": 0,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 0,
    "centerValY": 0,
    "leftVal": 100,
    "rightVal": 0,
    "topVal": 0,
    "bottomVal": 100
  },
  "M": {
    "offsetLeft": 0,
    "offsetRight": 0,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 0,
    "centerValY": 100,
    "leftVal": 100,
    "rightVal": 100,
    "topVal": 100,
    "bottomVal": 0
  },
  "N": {
    "offsetLeft": 0,
    "offsetRight": 0,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 0,
    "centerValY": 0,
    "leftVal": 100,
    "rightVal": 100,
    "topVal": 100,
    "bottomVal": 0
  },
  "O": {

    "offsetLeft": 0,
    "offsetRight": 0,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 0,
    "centerValY": 0,
    "leftVal": 100,
    "rightVal": 100,
    "topVal": 100,
    "bottomVal": 100
  },
  "P": {
    "offsetLeft": 0,
    "offsetRight": -25,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 100,
    "centerValY": 0,
    "leftVal": 100,
    "rightVal": 50,
    "topVal": 100,
    "bottomVal": 0
  },
  "Q": {
    "offsetLeft": -25,
    "offsetRight": 0,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 100,
    "centerValY": 0,
    "leftVal": 50,
    "rightVal": 100,
    "topVal": 100,
    "bottomVal": 0
  },
  "R": {

    "offsetLeft": 0,
    "offsetRight": 10,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 100,
    "centerValY": 0,
    "leftVal": 100,
    "rightVal": 80,
    "topVal": 60,
    "bottomVal": 0
  },
  "S": {

    "offsetLeft": -25,
    "offsetRight": 25,
    "offsetTop": 10,
    "offsetBottom": -10,
    "centerValX": 60,
    "centerValY": 0,
    "leftVal": 12.5,
    "rightVal": 12.5,
    "topVal": 80,
    "bottomVal": 80
  },
  "T": {
    "offsetLeft": 0,
    "offsetRight": 0,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 0,
    "centerValY": 100,
    "leftVal": 0,
    "rightVal": 0,
    "topVal": 100,
    "bottomVal": 0
  },
  "U": {
    "offsetLeft": 0,
    "offsetRight": 0,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 0,
    "centerValY": 0,
    "leftVal": 100,
    "rightVal": 100,
    "topVal": 0,
    "bottomVal": 100
  },
  "V": {
    "offsetLeft": -10,
    "offsetRight": -10,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 0,
    "centerValY": 0,
    "leftVal": 80,
    "rightVal": 80,
    "topVal": 00,
    "bottomVal": 60
  },
  "W": {

    "offsetLeft": 0,
    "offsetRight": 0,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 0,
    "centerValY": 100,
    "leftVal": 100,
    "rightVal": 100,
    "topVal": 0,
    "bottomVal": 100
  },
  "X": {
    "offsetLeft": 50,
    "offsetRight": -50,
    "offsetTop": -50,
    "offsetBottom": 50,
    "centerValX": 80,
    "centerValY": 80,
    "leftVal": 0,
    "rightVal": 0,
    "topVal": 0,
    "bottomVal": 0
  },
  "Y": {
    "offsetLeft": -25,
    "offsetRight": 0,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 100,
    "centerValY": 0,
    "leftVal": 50,
    "rightVal": 100,
    "topVal": 0,
    "bottomVal": 100
  },
  "Z": {
    "offsetLeft": 25,
    "offsetRight": -25,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 100,
    "centerValY": 0,
    "leftVal": 50,
    "rightVal": 50,
    "topVal": 100,
    "bottomVal": 100
  },
  "0": {
    "offsetLeft": 0,
    "offsetRight": 0,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 0,
    "centerValY": 100,
    "leftVal": 100,
    "rightVal": 100,
    "topVal": 100,
    "bottomVal": 100
  },
  "1": {
    "offsetLeft": 0,
    "offsetRight": 0,
    "offsetTop": -25,
    "offsetBottom": 0,
    "centerValX": 0,
    "centerValY": 100,
    "leftVal": 0,
    "rightVal": 0,
    "topVal": 50,
    "bottomVal": 100
  },
  "2": {
    "offsetLeft": 25,
    "offsetRight": -25,
    "offsetTop": -10,
    "offsetBottom": 0,
    "centerValX": 60,
    "centerValY": 0,
    "leftVal": 50,
    "rightVal": 12.5,
    "topVal": 80,
    "bottomVal": 100
  },
  "3": {
    "offsetLeft": 0,
    "offsetRight": 0,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 100,
    "centerValY": 0,
    "leftVal": 0,
    "rightVal": 100,
    "topVal": 100,
    "bottomVal": 100
  },
  "4": {
    "offsetLeft": -25,
    "offsetRight": 0,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 100,
    "centerValY": 0,
    "leftVal": 50,
    "rightVal": 100,
    "topVal": 0,
    "bottomVal": 0
  },
  "5": {
    "offsetLeft": -25,
    "offsetRight": 25,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 100,
    "centerValY": 0,
    "leftVal": 50,
    "rightVal": 50,
    "topVal": 100,
    "bottomVal": 100
  },
  "6": {
    "offsetLeft": 0,
    "offsetRight": 25,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 100,
    "centerValY": 0,
    "leftVal": 100,
    "rightVal": 50,
    "topVal": 100,
    "bottomVal": 100
  },
  "7": {
    "offsetLeft": 0,
    "offsetRight": 0,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 0,
    "centerValY": 0,
    "leftVal": 0,
    "rightVal": 100,
    "topVal": 100,
    "bottomVal": 0
  },
  "8": {
    "offsetLeft": 0,
    "offsetRight": 0,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 100,
    "centerValY": 0,
    "leftVal": 100,
    "rightVal": 100,
    "topVal": 100,
    "bottomVal": 100
  },
  "9": {
    "offsetLeft": -25,
    "offsetRight": 0,
    "offsetTop": 0,
    "offsetBottom": 0,
    "centerValX": 100,
    "centerValY": 0,
    "leftVal": 50,
    "rightVal": 100,
    "topVal": 100,
    "bottomVal": 100
  }

}
