
const one_unit = 30; // one square.
const alphabet = {
  "default": {
    p1offsetX: one_unit,
    p1offsetY: one_unit*2,
    p2offsetX: one_unit,
    p2offsetY: one_unit*2,
    p3offsetX: one_unit,
    p3offsetY: one_unit*2,
    p4offsetX: one_unit ,
    p4offsetY: one_unit*2,
    p5offsetX: one_unit,
    p5offsetY: one_unit*2,
    p6offsetX: one_unit,
    p6offsetY: one_unit*2,
    p7offsetX: one_unit,
    p7offsetY: one_unit*2,
    p8offsetX: one_unit,
    p8offsetY: one_unit*2,
  },
  "A": {
    p1offsetX: 0,
    p1offsetY: 0,
    p2offsetX: 0,
    p2offsetY: one_unit,
    p3offsetX: one_unit,
    p3offsetY: one_unit,
    p4offsetX: one_unit * 2,
    p4offsetY: one_unit,
    p5offsetX: 0,
    p5offsetY: one_unit * 2,
    p6offsetX: one_unit,
    p6offsetY: -one_unit,
    p7offsetX: one_unit * 2,
    p7offsetY: 0,
    p8offsetX: one_unit * 2,
    p8offsetY: one_unit * 2,
  },
  "B": {
    p1offsetX: 0,
    p1offsetY: -one_unit,
    p2offsetX: 0,
    p2offsetY: 0,
    p3offsetX: 0,
    p3offsetY: one_unit,
    p4offsetX: one_unit * 2,
    p4offsetY: one_unit,
    p5offsetX: one_unit,
    p5offsetY: one_unit / 2,
    p6offsetX: one_unit,
    p6offsetY: one_unit * 2,
    p7offsetX: 0,
    p7offsetY: one_unit * 2,
    p8offsetX: 0,
    p8offsetY: -one_unit,
  },
  "C": {
    p1offsetX: 0,
    p1offsetY: 0,
    p2offsetX: 0,
    p2offsetY: 0,
    p3offsetX: 0,
    p3offsetY: one_unit,
    p4offsetX: 0,
    p4offsetY: one_unit,
    p5offsetX: one_unit,
    p5offsetY: one_unit * 2,
    p6offsetX: one_unit * 2,
    p6offsetY: one_unit * 2,
    p7offsetX: one_unit,
    p7offsetY: -one_unit,
    p8offsetX: one_unit * 2,
    p8offsetY: -one_unit,
  },
  "D": {
    p1offsetX: 0,
    p1offsetY: -one_unit,
    p2offsetX: 0,
    p2offsetY: 0,
    p3offsetX: 0,
    p3offsetY: one_unit,
    p4offsetX: 0,
    p4offsetY: one_unit * 2,
    p5offsetX: one_unit,
    p5offsetY: one_unit * 2,
    p6offsetX: one_unit * 2,
    p6offsetY: one_unit,
    p7offsetX: one_unit,
    p7offsetY: -one_unit,
    p8offsetX: one_unit * 2,
    p8offsetY: 0,
  },
  "E": {
    p1offsetX: 0,
    p1offsetY: 0,
    p2offsetX: 0,
    p2offsetY: 0,
    p3offsetX: 0,
    p3offsetY: one_unit,
    p4offsetX: one_unit,
    p4offsetY: one_unit * 2,
    p5offsetX: one_unit * 2,
    p5offsetY: one_unit * 2,
    p6offsetX: one_unit,
    p6offsetY: one_unit / 2,
    p7offsetX: one_unit,
    p7offsetY: -one_unit,
    p8offsetX: one_unit * 2,
    p8offsetY: -one_unit,
  },
  "F": {
    p1offsetX: 0,
    p1offsetY: 0,
    p2offsetX: 0,
    p2offsetY: 0,
    p3offsetX: 0,
    p3offsetY: one_unit,
    p4offsetX: 0,
    p4offsetY: one_unit * 2,
    p5offsetX: one_unit,
    p5offsetY: one_unit,
    p6offsetX: one_unit,
    p6offsetY: one_unit,
    p7offsetX: one_unit,
    p7offsetY: -one_unit,
    p8offsetX: one_unit * 2,
    p8offsetY: -one_unit,
  },
  "G": {
    p1offsetX: one_unit * 2,
    p1offsetY: one_unit,
    p2offsetX: 0,
    p2offsetY: 0,
    p3offsetX: 0,
    p3offsetY: one_unit,
    p4offsetX: 0,
    p4offsetY: one_unit,
    p5offsetX: one_unit,
    p5offsetY: one_unit * 2,
    p6offsetX: one_unit * 2,
    p6offsetY: one_unit * 2,
    p7offsetX: one_unit,
    p7offsetY: -one_unit,
    p8offsetX: one_unit * 2,
    p8offsetY: -one_unit,
  },
  'H': {
    p1offsetX: 0,
    p1offsetY: 0,
    p2offsetX: 0,
    p2offsetY: one_unit,
    p3offsetX: one_unit,
    p3offsetY: one_unit,
    p4offsetX: one_unit * 2,
    p4offsetY: one_unit,
    p5offsetX: 0,
    p5offsetY: one_unit * 2,
    p6offsetX: 0,
    p6offsetY: 0,
    p7offsetX: one_unit * 2,
    p7offsetY: 0,
    p8offsetX: one_unit * 2,
    p8offsetY: one_unit * 2,
  },
  'I': {
    p1offsetX: one_unit,
    p1offsetY: 0,
    p2offsetX: one_unit,
    p2offsetY: one_unit,
    p3offsetX: one_unit,
    p3offsetY: -one_unit,
    p4offsetX: one_unit * 2,
    p4offsetY: one_unit * 2,
    p5offsetX: 0,
    p5offsetY: one_unit * 2,
    p6offsetX: one_unit,
    p6offsetY: one_unit * 2,
    p7offsetX: one_unit * 2,
    p7offsetY: -one_unit,
    p8offsetX: 0,
    p8offsetY: -one_unit,
  },
  'J': {
    p1offsetX: one_unit * 2,
    p1offsetY: 0,
    p2offsetX: one_unit * 2,
    p2offsetY: one_unit,
    p3offsetX: one_unit,
    p3offsetY: -one_unit,
    p4offsetX: 0,
    p4offsetY: one_unit,
    p5offsetX: 0,
    p5offsetY: one_unit,
    p6offsetX: one_unit,
    p6offsetY: one_unit * 2,
    p7offsetX: one_unit * 2,
    p7offsetY: -one_unit,
    p8offsetX: 0,
    p8offsetY: -one_unit,
  },
  "K": {
    p1offsetX: 0,
    p1offsetY: -one_unit,
    p2offsetX: 0,
    p2offsetY: 0,
    p3offsetX: 0,
    p3offsetY: one_unit,
    p4offsetX: 0,
    p4offsetY: one_unit * 2,
    p5offsetX: one_unit,
    p5offsetY: one_unit,
    p6offsetX: one_unit * 2,
    p6offsetY: one_unit * 2,
    p7offsetX: one_unit * 2,
    p7offsetY: 0,
    p8offsetX: 0,
    p8offsetY: 0,
  },
  "L": {
    p1offsetX: 0,
    p1offsetY: -one_unit,
    p2offsetX: 0,
    p2offsetY: 0,
    p3offsetX: 0,
    p3offsetY: one_unit,
    p4offsetX: 0,
    p4offsetY: one_unit * 2,
    p5offsetX: one_unit,
    p5offsetY: one_unit * 2,
    p6offsetX: one_unit * 2,
    p6offsetY: one_unit * 2,
    p7offsetX: 0,
    p7offsetY: 0,
    p8offsetX: 0,
    p8offsetY: 0,
  },
  "M": {
    p1offsetX: 0,
    p1offsetY: 0,
    p2offsetX: 0,
    p2offsetY: one_unit,
    p3offsetX: one_unit,
    p3offsetY: one_unit / 3,
    p4offsetX: one_unit * 2,
    p4offsetY: one_unit,
    p5offsetX: 0,
    p5offsetY: one_unit * 2,
    p6offsetX: 0,
    p6offsetY: 0,
    p7offsetX: one_unit * 2,
    p7offsetY: 0,
    p8offsetX: one_unit * 2,
    p8offsetY: one_unit * 2,
  },
  "N": {
    p1offsetX: 0,
    p1offsetY: 0,
    p2offsetX: 0,
    p2offsetY: one_unit,
    p3offsetX: one_unit,
    p3offsetY: 0,
    p4offsetX: one_unit * 2,
    p4offsetY: one_unit,
    p5offsetX: 0,
    p5offsetY: one_unit * 2,
    p6offsetX: 0,
    p6offsetY: 0,
    p7offsetX: one_unit * 2,
    p7offsetY: 0,
    p8offsetX: one_unit * 2,
    p8offsetY: one_unit * 2,
  },
  "O": {
    p1offsetX: 0,
    p1offsetY: 0,
    p2offsetX: 0,
    p2offsetY: one_unit,
    p3offsetX: one_unit,
    p3offsetY: one_unit * 2,
    p4offsetX: one_unit * 2,
    p4offsetY: one_unit,
    p5offsetX: 0,
    p5offsetY: one_unit * 2,
    p6offsetX: one_unit,
    p6offsetY: 0,
    p7offsetX: one_unit * 2,
    p7offsetY: 0,
    p8offsetX: one_unit * 2,
    p8offsetY: one_unit * 2,
  },
  "P": {
    p1offsetX: 0,
    p1offsetY: -one_unit,
    p2offsetX: 0,
    p2offsetY: 0,
    p3offsetX: 0,
    p3offsetY: one_unit,
    p4offsetX: 0,
    p4offsetY: one_unit * 2,
    p5offsetX: one_unit,
    p5offsetY: -one_unit,
    p6offsetX: one_unit * 2,
    p6offsetY: 0,
    p7offsetX: one_unit,
    p7offsetY: one_unit,
    p8offsetX: 0,
    p8offsetY: 0,
  },
  "Q": {
    p1offsetX: one_unit * 2,
    p1offsetY: -one_unit,
    p2offsetX: 0,
    p2offsetY: 0,
    p3offsetX: one_unit * 2,
    p3offsetY: one_unit,
    p4offsetX: one_unit * 2,
    p4offsetY: one_unit * 2,
    p5offsetX: one_unit,
    p5offsetY: -one_unit,
    p6offsetX: one_unit * 2,
    p6offsetY: 0,
    p7offsetX: one_unit,
    p7offsetY: one_unit,
    p8offsetX: 0,
    p8offsetY: 0,

  },
  "R": {
    p1offsetX: 0,
    p1offsetY: -one_unit,
    p2offsetX: 0,
    p2offsetY: 0,
    p3offsetX: 0,
    p3offsetY: one_unit,
    p4offsetX: 0,
    p4offsetY: one_unit * 2,
    p5offsetX: one_unit,
    p5offsetY: -one_unit,
    p6offsetX: one_unit * 2,
    p6offsetY: 0,
    p7offsetX: one_unit,
    p7offsetY: one_unit,
    p8offsetX: one_unit * 2,
    p8offsetY: one_unit * 2,
  },
  "S": {
    p1offsetX: one_unit * 2,
    p1offsetY: -one_unit,
    p2offsetX: 0,
    p2offsetY: 0,
    p3offsetX: one_unit,
    p3offsetY: one_unit * 2,
    p4offsetX: 0,
    p4offsetY: one_unit * 2,
    p5offsetX: one_unit,
    p5offsetY: -one_unit,
    p6offsetX: one_unit * 2,
    p6offsetY: one_unit / 2,
    p7offsetX: one_unit,
    p7offsetY: one_unit / 2,
    p8offsetX: one_unit * 2,
    p8offsetY: (one_unit * 2) * 0.75,
  },
  'T': {
    p1offsetX: one_unit,
    p1offsetY: 0,
    p2offsetX: one_unit,
    p2offsetY: one_unit,
    p3offsetX: one_unit,
    p3offsetY: -one_unit,
    p4offsetX: 0,
    p4offsetY: -one_unit,
    p5offsetX: one_unit,
    p5offsetY: one_unit * 2,
    p6offsetX: 0,
    p6offsetY: -one_unit,
    p7offsetX: one_unit * 2,
    p7offsetY: -one_unit,
    p8offsetX: 0,
    p8offsetY: -one_unit,
  },
  "U": {
    p1offsetX: 0,
    p1offsetY: 0,
    p2offsetX: 0,
    p2offsetY: one_unit,
    p3offsetX: one_unit,
    p3offsetY: one_unit * 2,
    p4offsetX: one_unit * 2,
    p4offsetY: one_unit,
    p5offsetX: 0,
    p5offsetY: one_unit * 2,
    p6offsetX: 0,
    p6offsetY: 0,
    p7offsetX: one_unit * 2,
    p7offsetY: 0,
    p8offsetX: one_unit * 2,
    p8offsetY: one_unit * 2,
  },
  "V": {
    p1offsetX: 0,
    p1offsetY: 0,
    p2offsetX: 0,
    p2offsetY: one_unit,
    p3offsetX: one_unit,
    p3offsetY: one_unit * 2,
    p4offsetX: one_unit * 2,
    p4offsetY: one_unit,
    p5offsetX: one_unit,
    p5offsetY: one_unit * 2,
    p6offsetX: 0,
    p6offsetY: 0,
    p7offsetX: one_unit * 2,
    p7offsetY: 0,
    p8offsetX: one_unit,
    p8offsetY: one_unit * 2,
  },
  "W": {
    p1offsetX: 0,
    p1offsetY: 0,
    p2offsetX: 0,
    p2offsetY: one_unit,
    p3offsetX: one_unit,
    p3offsetY: (one_unit / 1.5) + one_unit,
    p4offsetX: one_unit * 2,
    p4offsetY: one_unit,
    p5offsetX: 0,
    p5offsetY: one_unit * 2,
    p6offsetX: 0,
    p6offsetY: 0,
    p7offsetX: one_unit * 2,
    p7offsetY: 0,
    p8offsetX: one_unit * 2,
    p8offsetY: one_unit * 2,
  },
  "X": {
    p1offsetX: 0,
    p1offsetY: 0,
    p2offsetX: one_unit,
    p2offsetY: one_unit,
    p3offsetX: one_unit * 2,
    p3offsetY: one_unit * 2,
    p4offsetX: 0,
    p4offsetY: one_unit * 2,
    p5offsetX: 0,
    p5offsetY: one_unit * 2,
    p6offsetX: 0,
    p6offsetY: 0,
    p7offsetX: one_unit * 2,
    p7offsetY: 0,
    p8offsetX: one_unit * 2,
    p8offsetY: one_unit * 2,
  },
  "Y": {
    p1offsetX: 0,
    p1offsetY: one_unit,
    p2offsetX: one_unit,
    p2offsetY: one_unit * 2,
    p3offsetX: one_unit * 2,
    p3offsetY: one_unit,
    p4offsetX: one_unit * 2,
    p4offsetY: one_unit * 2,
    p5offsetX: one_unit * 2,
    p5offsetY: one_unit * 3,
    p6offsetX: 0,
    p6offsetY: one_unit * 3 + one_unit / 2,
    p7offsetX: one_unit,
    p7offsetY: one_unit * 4,
    p8offsetX: one_unit * 2,
    p8offsetY: one_unit * 2,
  },
  "Z": {
    p1offsetX: 0,
    p1offsetY: -one_unit,
    p2offsetX: one_unit,
    p2offsetY: -one_unit,
    p3offsetX: one_unit * 2,
    p3offsetY: -one_unit,
    p4offsetX: one_unit,
    p4offsetY: one_unit,
    p5offsetX: 0,
    p5offsetY: one_unit * 2,
    p6offsetX: one_unit,
    p6offsetY: one_unit * 2,
    p7offsetX: one_unit * 2,
    p7offsetY: 0,
    p8offsetX: one_unit * 2,
    p8offsetY: one_unit * 2,
  },
  "0": {
    p1offsetX: 0,
    p1offsetY: 0,
    p2offsetX: 0,
    p2offsetY: one_unit,
    p3offsetX: one_unit,
    p3offsetY: one_unit * 2,
    p4offsetX: one_unit * 2,
    p4offsetY: one_unit,
    p5offsetX: one_unit,
    p5offsetY: one_unit * 2,
    p6offsetX: one_unit,
    p6offsetY: -one_unit,
    p7offsetX: one_unit * 2,
    p7offsetY: 0,
    p8offsetX: one_unit,
    p8offsetY: one_unit * 2,
  },
  "1": {
    p1offsetX: 0,
    p1offsetY: 0,
    p2offsetX: one_unit,
    p2offsetY: -one_unit,
    p3offsetX: one_unit,
    p3offsetY: 0,
    p4offsetX: one_unit,
    p4offsetY: one_unit,
    p5offsetX: one_unit,
    p5offsetY: one_unit * 2,
    p6offsetX: 0,
    p6offsetY: one_unit * 2,
    p7offsetX: 0,
    p7offsetY: 0,
    p8offsetX: one_unit * 2,
    p8offsetY: one_unit * 2,
  },
  "2": {
    p1offsetX: 0,
    p1offsetY: 0 - one_unit / 2,
    p2offsetX: one_unit,
    p2offsetY: -one_unit,
    p3offsetX: one_unit * 2,
    p3offsetY: 0,
    p4offsetX: one_unit,
    p4offsetY: one_unit,
    p5offsetX: 0,
    p5offsetY: one_unit * 2,
    p6offsetX: one_unit,
    p6offsetY: one_unit * 2,
    p7offsetX: one_unit * 2,
    p7offsetY: one_unit * 2,
    p8offsetX: 0,
    p8offsetY: 0 - one_unit / 2,
  },
  "3": {
    p1offsetX: 0,
    p1offsetY: -one_unit,
    p2offsetX: one_unit,
    p2offsetY: -one_unit,
    p3offsetX: one_unit * 2,
    p3offsetY: 0,
    p4offsetX: one_unit * 2,
    p4offsetY: one_unit,
    p5offsetX: one_unit,
    p5offsetY: one_unit / 2,
    p6offsetX: one_unit,
    p6offsetY: one_unit * 2,
    p7offsetX: 0,
    p7offsetY: one_unit * 2,
    p8offsetX: 0,
    p8offsetY: -one_unit,
  },
  "4": {
    p1offsetX: 0,
    p1offsetY: -one_unit,
    p2offsetX: 0,
    p2offsetY: 0,
    p3offsetX: 0,
    p3offsetY: one_unit,
    p4offsetX: one_unit * 2,
    p4offsetY: one_unit,
    p5offsetX: one_unit,
    p5offsetY: one_unit,
    p6offsetX: one_unit,
    p6offsetY: one_unit * 2,
    p7offsetX: 0,
    p7offsetY: one_unit,
    p8offsetX: 0,
    p8offsetY: -one_unit,
  },
  "5": {
    p1offsetX: 0,
    p1offsetY: -one_unit * 2,
    p2offsetX: one_unit,
    p2offsetY: -one_unit * 2,
    p3offsetX: one_unit * 2,
    p3offsetY: -one_unit * 2,
    p4offsetX: 0,
    p4offsetY: -one_unit,
    p5offsetX: one_unit,
    p5offsetY: 0,
    p6offsetX: one_unit * 2,
    p6offsetY: one_unit,
    p7offsetX: one_unit,
    p7offsetY: one_unit * 2,
    p8offsetX: 0,
    p8offsetY: one_unit * 2,
  },
  "6": {
    // CAN IMPROVE
    p1offsetX: one_unit / 2,
    p1offsetY: -one_unit,
    p2offsetX: 0,
    p2offsetY: 0,
    p3offsetX: 0,
    p3offsetY: one_unit,
    p4offsetX: one_unit * 2,
    p4offsetY: one_unit,
    p5offsetX: one_unit,
    p5offsetY: one_unit / 2,
    p6offsetX: one_unit,
    p6offsetY: one_unit * 2,
    p7offsetX: 0,
    p7offsetY: 0,
    p8offsetX: one_unit / 2,
    p8offsetY: -one_unit,
  },
  "7": {
    p1offsetX: 0,
    p1offsetY: -one_unit,
    p2offsetX: one_unit,
    p2offsetY: -one_unit,
    p3offsetX: one_unit * 2,
    p3offsetY: -one_unit,
    p4offsetX: one_unit * 2,
    p4offsetY: 0,
    p5offsetX: one_unit,
    p5offsetY: one_unit,
    p6offsetX: one_unit,
    p6offsetY: one_unit * 2,
    p7offsetX: one_unit * 2,
    p7offsetY: 0,
    p8offsetX: one_unit * 2,
    p8offsetY: -one_unit,
  },
  "8": {
    p1offsetX: one_unit,
    p1offsetY: -one_unit * 2,
    p2offsetX: 0,
    p2offsetY: -one_unit,
    p3offsetX: one_unit * 2,
    p3offsetY: -one_unit,
    p4offsetX: one_unit,
    p4offsetY: 0,
    p5offsetX: 0,
    p5offsetY: one_unit,
    p6offsetX: one_unit,
    p6offsetY: one_unit * 2,
    p7offsetX: one_unit * 2,
    p7offsetY: one_unit,
    p8offsetX: one_unit * 2,
    p8offsetY: -one_unit,
  },
  9: {
    p1offsetX: 0,
    p1offsetY: 0,
    p2offsetX: 0,
    p2offsetY: 0,
    p3offsetX: one_unit * 2,
    p3offsetY: one_unit,
    p4offsetX: one_unit * 2,
    p4offsetY: one_unit * 2,
    p5offsetX: one_unit,
    p5offsetY: -one_unit,
    p6offsetX: one_unit * 2,
    p6offsetY: 0,
    p7offsetX: one_unit,
    p7offsetY: one_unit,
    p8offsetX: 0,
    p8offsetY: 0
  }
}