const letterSize = 50;
const letterAngle = 0.872665;

const alphabet = {
  "default": {
    "p1": { "ang": 000,   "dist": 0},
    "p2": { "ang": 000,   "dist": 0},
    "p3": { "ang": 000,   "dist": 0},
    "p4": { "ang": 000,   "dist": 0},
    "p5": { "ang": 000,   "dist": 0},
    "p6": { "ang": 000,   "dist": 0},
    },
  "A": {
    "p1": { "ang":  000,   "dist": letterSize},
    "p2": { "ang": -129,   "dist": letterSize},
    "p3": { "ang":  051,   "dist": 0.4414*(letterSize)},
    "p4": { "ang":  000,   "dist": letterSize},
    "p5": { "ang":  129,   "dist": letterSize},
    "p6": { "ang": -051,   "dist": 0.4414*(letterSize)},
  },
  "B": {
    "p1": { "ang": -037,   "dist": letterSize},
    "p2": { "ang": 129,   "dist": letterSize},
    "p3": { "ang": -148,   "dist": letterSize},
    "p4": { "ang": -037,   "dist": letterSize},
    "p5": { "ang": 063,   "dist": letterSize},
    "p6": { "ang": -148,   "dist": letterSize},
  },
  "C": {
    "p1": { "ang": -090,   "dist": letterSize},
    "p2": { "ang": 158,   "dist": letterSize},
    "p3": { "ang": -026,   "dist": 0.5704*letterSize},
    "p4": { "ang": -90,   "dist": letterSize},
    "p5": { "ang": 026,   "dist": letterSize},
    "p6": { "ang": 202,   "dist": 0.5704*letterSize},
  },
  "D": {
    "p1": { "ang": 090,   "dist": 0.9*letterSize},
    "p2": { "ang": -035,   "dist": letterSize},
    "p3": { "ang": -150,   "dist": letterSize},
    "p4": { "ang": 090,   "dist": 0.32*letterSize},
    "p5": { "ang": -035,   "dist": letterSize},
    "p6": { "ang": -150,   "dist": letterSize},
  },
  "E": {
    "p1": { "ang": -090,   "dist": 0.8*letterSize},
    "p2": { "ang": 019,   "dist": letterSize},
    "p3": { "ang": 160,   "dist": letterSize},
    "p4": { "ang": 090,   "dist": letterSize},
    "p5": { "ang": -035,   "dist": 0.5*letterSize},
    "p6": { "ang": -150,   "dist": 0.5*letterSize},
  },
  "F": {
    "p1": { "ang": -012,   "dist": letterSize},
    "p2": { "ang": -170,   "dist": letterSize},
    "p3": { "ang": -064,   "dist": letterSize},
    "p4": { "ang": -012,   "dist": letterSize},
    "p5": { "ang": -064,   "dist": letterSize},
    "p6": { "ang": 064,   "dist": letterSize},
  },
    "G": {
    "p1": { "ang": 033,   "dist": letterSize},
    "p2": { "ang": 153,   "dist": letterSize},
    "p3": { "ang": -090,   "dist": letterSize},
    "p4": { "ang": 153,   "dist": letterSize},
    "p5": { "ang": 180,   "dist": 0.6131*letterSize},
    "p6": { "ang": 90,   "dist": letterSize},
  },
    "H": {
    "p1": { "ang": -052,   "dist": letterSize},
    "p2": { "ang": 000,   "dist": 0},
    "p3": { "ang": -138,   "dist": letterSize},
    "p4": { "ang": 000,   "dist": 0},
    "p5": { "ang": 052,   "dist": letterSize},
    "p6": { "ang": 138,   "dist": letterSize},
  },
    "I": {
    "p1": { "ang": -032,   "dist": letterSize},
    "p2": { "ang": 000,   "dist": letterSize},
    "p3": { "ang": 180,   "dist": letterSize},
    "p4": { "ang": 000,   "dist": 0.7*letterSize},
    "p5": { "ang": 028,   "dist": 0.6565*letterSize},
    "p6": { "ang": 180,   "dist": letterSize},
  },
    "J": {
    "p1": { "ang": 148,   "dist": letterSize},
    "p2": { "ang": 000,   "dist": letterSize},
    "p3": { "ang": 180,   "dist": letterSize},
    "p4": { "ang": 148,   "dist": letterSize},
    "p5": { "ang": -106,   "dist": letterSize},
    "p6": { "ang": 180,   "dist": letterSize},
  },
    "K": {
    "p1": { "ang": -128,   "dist": letterSize},
    "p2": { "ang": -90,   "dist": 0.7846*letterSize},
    "p3": { "ang": 064,   "dist": letterSize},
    "p4": { "ang": 128,   "dist": letterSize},
    "p5": { "ang": -064,   "dist": letterSize},
    "p6": { "ang": -090,   "dist": 0.7846*letterSize},
  },
    "L": {
    "p1": { "ang": 130,   "dist": letterSize},
    "p2": { "ang": -170,   "dist": letterSize},
    "p3": { "ang": -130,   "dist": letterSize},
    "p4": { "ang": -012,   "dist": letterSize},
    "p5": { "ang": -170,   "dist": letterSize},
    "p6": { "ang": -130,   "dist": letterSize},
  },
  "M": {
    "p1": { "ang": 129-90,   "dist": letterSize},
    "p2": { "ang": 000,   "dist": 0.2*letterSize},
    "p3": { "ang": -148-90,   "dist": letterSize},
    "p4": { "ang": 063-90,   "dist": letterSize},
    "p5": { "ang": -037-90,   "dist": letterSize},
    "p6": { "ang": 000,   "dist": 0.2*letterSize},
  },
  "N": {
    "p1": { "ang": -052,   "dist": letterSize},
    "p2": { "ang": 180,   "dist": 0.75*letterSize},
    "p3": { "ang": -138,   "dist": letterSize},
    "p4": { "ang": 180,   "dist": 0.75*letterSize},
    "p5": { "ang": 000,   "dist": 1*letterSize},
    "p6": { "ang": 138,   "dist": letterSize},
  },
  "O": {
    "p1": { "ang": 90,   "dist": 0.8*letterSize},
    "p2": { "ang": 180,   "dist": 0.8*letterSize},
    "p3": { "ang": -90,   "dist": 0.8*letterSize},
    "p4": { "ang": 090,   "dist": 0.8*letterSize},
    "p5": { "ang": -90,   "dist": 0.8*letterSize},
    "p6": { "ang": 000,   "dist": 0.8*letterSize},
  },
  "P": {
    "p1": { "ang": 0,   "dist": letterSize},
    "p2": { "ang": -180,   "dist": letterSize},
    "p3": { "ang": -050,   "dist": letterSize},
    "p4": { "ang": 0,   "dist": letterSize},
    "p5": { "ang": 0,   "dist": 0},
    "p6": { "ang": 070,   "dist": letterSize},
  },
  "Q": {
    "p1": { "ang": 150,   "dist": letterSize},
    "p2": { "ang": 120,   "dist": 0.65*letterSize},
    "p3": { "ang": 180,   "dist": 0.34*letterSize},
    "p4": { "ang": 110,   "dist": letterSize},
    "p5": { "ang": 000,   "dist": letterSize},
    "p6": { "ang": -110,   "dist": letterSize},
  },
  "R": {
    "p1": { "ang": 060,   "dist": letterSize},
    "p2": { "ang": -039,   "dist": letterSize},
    "p3": { "ang": -141,   "dist": letterSize},
    "p4": { "ang": 000,   "dist": 0},
    "p5": { "ang": -090,   "dist": 0.6248*letterSize},
    "p6": { "ang": 135,   "dist": letterSize},
  },
  "S": {
    "p1": { "ang": 055,   "dist": letterSize},
    "p2": { "ang": -045,   "dist": letterSize},
    "p3": { "ang": -135,   "dist": 0.2*letterSize},
    "p4": { "ang": 145,   "dist": letterSize},
    "p5": { "ang": -135,   "dist": letterSize},
    "p6": { "ang": 055,   "dist": 0.2*letterSize},
  },
  "T": {
    "T": { "test" : 000},
    "p1": { "ang": 029,   "dist": 0.7392*letterSize},
    "p2": { "ang": -029,   "dist": 0.7392*letterSize},
    "p3": { "ang": -180,   "dist": letterSize},
    "p4": { "ang": -060,   "dist": letterSize},
    "p5": { "ang": 000,   "dist": 0.3*letterSize},
    "p6": { "ang": 060,   "dist": letterSize},
  },
  "U": {
    "p1": { "ang": 180,   "dist": letterSize},
    "p2": { "ang": 051,   "dist": letterSize},
    "p3": { "ang": 142,   "dist": letterSize},
    "p4": { "ang": 180,   "dist": letterSize},
    "p5": { "ang": -051,   "dist": letterSize},
    "p6": { "ang": -142,   "dist": letterSize},
  },
  "V": {
    "p1": { "ang":  180,   "dist": letterSize},
    "p2": { "ang": -051,   "dist": letterSize},
    "p3": { "ang":  129,   "dist": 0.37*letterSize},
    "p4": { "ang":  180,   "dist": letterSize},
    "p5": { "ang":  051,   "dist": letterSize},
    "p6": { "ang": -129,   "dist": 0.37*letterSize},
  },
  "W": {
    "p1": { "ang": 037-90,   "dist": letterSize},
    "p2": { "ang": -129-90,   "dist": letterSize},
    "p3": { "ang": 148-90,   "dist": letterSize},
    "p4": { "ang": 037-90,   "dist": letterSize},
    "p5": { "ang": -063-90,   "dist": letterSize},
    "p6": { "ang": 148-90,   "dist": letterSize},
  },
  "X": {
    "p1": { "ang": 055,   "dist": letterSize},
    "p2": { "ang": -055,   "dist": letterSize},
    "p3": { "ang": 000,   "dist": 0},
    "p4": { "ang": 135,   "dist": letterSize},
    "p5": { "ang": -135,   "dist": letterSize},
    "p6": { "ang": 000,   "dist": 0},
  },
  "Y": {
    "p1": { "ang": 012,   "dist": 0.67*letterSize},
    "p2": { "ang": -170,   "dist": letterSize},
    "p3": { "ang": 064,   "dist": letterSize},
    "p4": { "ang": 012,   "dist": 0},
    "p5": { "ang": 064,   "dist": letterSize},
    "p6": { "ang": -054,   "dist": letterSize},
  },
  "Z": {
     "p1": { "ang": -055,   "dist": letterSize},
    "p2": { "ang": 045,   "dist": letterSize},
    "p3": { "ang": 135,   "dist": 0.2*letterSize},
    "p4": { "ang": -145,   "dist": letterSize},
    "p5": { "ang": 135,   "dist": letterSize},
    "p6": { "ang": -055,   "dist": 0.2*letterSize},
  },
  "0": {
    "p1": { "ang": 90,   "dist": 0.7*letterSize},
    "p2": { "ang": 180,   "dist": letterSize},
    "p3": { "ang": -90,   "dist": 0.7*letterSize},
    "p4": { "ang": 090,   "dist": 0.7*letterSize},
    "p5": { "ang": -90,   "dist": 0.7*letterSize},
    "p6": { "ang": 000,   "dist": letterSize},
  },  
    "1": {
    "p1": { "ang": 0,   "dist": letterSize},
    "p2": { "ang": 180,   "dist": letterSize},
    "p3": { "ang": 040,   "dist": letterSize},
    "p4": { "ang": 0,   "dist": letterSize},
    "p5": { "ang": 040,   "dist": letterSize},
    "p6": { "ang": -060,   "dist": letterSize},
  },  
    "2": {
    "p1": { "ang": -037-180,   "dist": letterSize},
    "p2": { "ang": 100-180,   "dist": letterSize},
    "p3": { "ang": -148-180,   "dist": letterSize},
    "p4": { "ang": -037-180,   "dist": letterSize},
    "p5": { "ang": 037-180,   "dist": letterSize},
    "p6": { "ang": -075-180,   "dist": 0.6*letterSize},
  },  
    "3": {
    "p1": { "ang": 129,   "dist": letterSize},
    "p2": { "ang": 090,   "dist": 0.2*letterSize},
    "p3": { "ang": -148,   "dist": letterSize},
    "p4": { "ang": 063,   "dist": letterSize},
    "p5": { "ang": -037,   "dist": letterSize},
    "p6": { "ang": 090,   "dist": 0.2*letterSize},
  },
    "4": {
    "p1": { "ang": 000,   "dist": -0.3*letterSize},
    "p2": { "ang": 000,   "dist": letterSize},
    "p3": { "ang": -110,   "dist": 0.8*letterSize},
    "p4": { "ang": 180,   "dist": -0.3*letterSize},
    "p5": { "ang": 70,   "dist": 0.8*letterSize},
    "p6": { "ang": 180,   "dist": letterSize},
  },  
    "5": {
    "p1": { "ang": -037,   "dist": letterSize},
    "p2": { "ang": 100,   "dist": letterSize},
    "p3": { "ang": -148,   "dist": letterSize},
    "p4": { "ang": -037,   "dist": letterSize},
    "p5": { "ang": 037,   "dist": letterSize},
    "p6": { "ang": -075,   "dist": 0.6*letterSize},
  },  
    "6": {
    "p1": { "ang": 0,   "dist": letterSize},
    "p2": { "ang": -180,   "dist": letterSize},
    "p3": { "ang": -140,   "dist": letterSize},
    "p4": { "ang": 0,   "dist": -letterSize},
    "p5": { "ang": 0,   "dist": 0},
    "p6": { "ang": 120,   "dist": letterSize},
  },  
    "7": {
    "p1": { "ang": 012,   "dist": letterSize},
    "p2": { "ang": 170,   "dist": letterSize},
    "p3": { "ang": 064,   "dist": letterSize},
    "p4": { "ang": 012,   "dist": letterSize},
    "p5": { "ang": 064,   "dist": letterSize},
    "p6": { "ang": -064,   "dist": letterSize},
  },  
    "8": {
    "p1": { "ang": 040,   "dist": letterSize},
    "p2": { "ang": -040,   "dist": letterSize},
    "p3": { "ang": 000,   "dist": 0},
    "p4": { "ang": 148,   "dist": letterSize},
    "p5": { "ang": -148,   "dist": letterSize},
    "p6": { "ang": 000,   "dist": 0},
  },  
    "9": {
    "p1": { "ang": 0,   "dist": letterSize},
    "p2": { "ang": 180,   "dist": letterSize},
    "p3": { "ang": 050,   "dist": letterSize},
    "p4": { "ang": 0,   "dist": letterSize},
    "p5": { "ang": 0,   "dist": 0},
    "p6": { "ang": -070,   "dist": letterSize},
  },   
  "?": {
    "p1": { "ang": 070,   "dist": letterSize},
    "p2": { "ang": -030,   "dist": letterSize},
    "p3": { "ang": -180,   "dist": 0.5*letterSize},
    "p4": { "ang": -170,   "dist": letterSize},
    "p5": { "ang": -180,   "dist": 0.6*letterSize},
    "p6": { "ang": 170,   "dist": letterSize},
  },
  "!": {
    "p1": { "ang": 020,   "dist": letterSize},
    "p2": { "ang": -020,   "dist": letterSize},
    "p3": { "ang": -180,   "dist": 0.5*letterSize},
    "p4": { "ang": -170,   "dist": letterSize},
    "p5": { "ang": -180,   "dist": 0.6*letterSize},
    "p6": { "ang": 170,   "dist": letterSize},
  },
  "-": {
    "p1": { "ang": 090,   "dist": 0.3*letterSize},
    "p2": { "ang": 0,   "dist": 0.3*letterSize},
    "p3": { "ang": -90,   "dist": 0.3*letterSize},
    "p4": { "ang": -090,   "dist": 0.3*letterSize},
    "p5": { "ang": 180,   "dist": 0.3*letterSize},
    "p6": { "ang": 090,   "dist": 0.3*letterSize},
  },
  " ": {
    "p1": { "ang": 090,   "dist": 0},
    "p2": { "ang": 0,   "dist": 0},
    "p3": { "ang": -90,   "dist": 0},
    "p4": { "ang": -090,   "dist": 0},
    "p5": { "ang": 180,   "dist": 0},
    "p6": { "ang": 090,   "dist": 0},
  },          
}